#!/usr/bin/env ruby
require 'rubygems'
require 'ArgsParser'
require 'em-websocket'
require 'rainbow'

parser = ArgsParser.parser
parser.bind(:port, :p, 'port (default : 8080)')
parser.bind(:help, :h, 'show help')
first, params = parser.parse(ARGV)

if parser.has_option(:help)
  puts parser.help
  exit
end

params[:port] = 8080 unless params[:port]
p params

EM::run do
  puts "start server port:#{params[:port].to_i}".color(:green)
  @channel = EM::Channel.new
  EM::WebSocket.start(:host => "0.0.0.0", :port => params[:port].to_i) do |ws|
    ws.onopen{
      sid = @channel.subscribe{|mes|
        ws.send(mes)
      }
      puts "<#{sid}> connected".color(:green)

      ws.onmessage{|mes|
        puts "receive <#{sid}> #{mes}".color(:magenta)
      }

      ws.onclose{
        puts "<#{sid}> disconnected".color(:green)
        @channel.unsubscribe(sid)
      }
    }
  end

  EM::defer do
    loop do
      line = gets.strip
      puts "send '#{line}'".color(:magenta)
      @channel.push(line)
    end
  end
  
end
