
# グラム : センサ値
weights :
    '0' : 756.35 # 何も載っていない
    '10' : 751.1 # 分銅
    '20' : 745.8 # 分銅
    '30' : 740.5 # 分銅

api : 'http://localhost:8093/'

browser : 'open'
# browser : 'google-chrome'
# browser : 'firefox'

serial_socket_gateway : 
    host : 'localhost'
    port : 8782
